### ISSUE TITLE
Does not install on Ubuntu?

### ISSUE THREAD

**Issue by tknerr** [mohitsethi/chef-atom#1]
Do I get it right that for Ubuntu / Debian only the PPA repo is added, but atom is not actually being installed?

Because right now I'm doing this:
```ruby
# sets up ppa launchpad repo
include_recipe "atom"

# install atom
package "atom" do
  action :install
end

# install plugins
atom_apm "minimap"
```

Just wondering because the README says "installs / configures atom.io" and for windows it looks like it's actually being installed at version `node[:atom][:version]`...

**Comment by ruffsl** [comment]
I'm not sure how this works either, even the 0.2 release.

**Comment by dougireton** [comment]
With the 0.20. 0 release it should install Atom on Ubuntu. Is that broken for you?

**Comment by ruffsl** [comment]
I guess I'm not sure how to use it to install just atom.
In the READ.ME, there is an example of how to install apm packages into atom in your recipe file,
but what type to instal just the IDE alone like the default section mentions?
``` ruby
atom 'default' do
  action :install
end
```
this?

**Comment by dougireton** [comment]
```ruby
include_recipe 'atom'
```

should do the trick
