### ISSUE TITLE
Why Docker?

### ISSUE THREAD

**Issue by dougireton** [mohitsethi/chef-atom#3]
I'm starting to refactor this cookbook, and noticed you used kitchen-docker. Any reason not to use straight Vagrant/VirtualBox, or kitchen-ec2? Docker adds more complexity to developing this cookbook on a Mac or Windows laptop.

**Comment by mohitsethi** [comment]
@dougireton i was comfortable using docker. Feel free to include vagrant or ec2 driver while you refactor.

**Comment by dougireton** [comment]
Cool, thanks.
